# Generated by Django 2.0.3 on 2018-04-06 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='asset',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='repository.Asset'),
            preserve_default=False,
        ),
    ]
