# Generated by Django 2.0.3 on 2018-04-06 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_server_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='asset',
        ),
    ]
