# Generated by Django 2.0.3 on 2018-04-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_server_latest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='latest_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近更新时间'),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_version',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='系统版本'),
        ),
        migrations.AlterField(
            model_name='server',
            name='sn',
            field=models.CharField(db_index=True, max_length=128, verbose_name='SN号'),
        ),
    ]
