# Generated by Django 2.0.3 on 2018-04-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_auto_20180407_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='server_type_id',
            field=models.IntegerField(choices=[(1, '上架'), (2, '在线'), (3, '离线'), (4, '下架')], default=1),
        ),
    ]
