# Generated by Django 2.0.3 on 2018-04-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_auto_20180408_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admininfo',
            options={'verbose_name_plural': '管理员用户表'},
        ),
        migrations.RenameField(
            model_name='server',
            old_name='server_type_id',
            new_name='server_status_id',
        ),
    ]
